# Generated by Django 3.0.7 on 2020-06-13 21:13

import datadesign.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200613_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(max_length=20, validators=[datadesign.api.validators.validate_level], verbose_name='Nível'),
        ),
    ]
