# Generated by Django 3.0.7 on 2020-06-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200613_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='Endereço IP'),
        ),
    ]
